apiVersion: v1
kind: ServiceAccount
metadata:
  name: assign-configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assign-configmaps
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - "create"
      - "delete"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assign-configmaps
subjects:
  - kind: ServiceAccount
    name: assign-configmaps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assign-configmaps
