apiVersion: v1
kind: ServiceAccount
metadata:
  name: everything
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: everything
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: everything
subjects:
  - kind: ServiceAccount
    name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
